site_name: SUGAR实验室知识库
site_url: https://lmh0921.github.io/lab-docs/
repo_url: https://github.com/lmh0921/lab-docs/
theme:
  name: material
  language: zh # 设置中文
  features:
    - navigation.tabs # 顶部导航栏模式
    - navigation.sections # 侧边栏折叠
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮

# 支持数学公式 (LaTeX)
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details # 支持折叠块（适合放代码或长推导）

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
